# Generated by Django 5.1.4 on 2025-06-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productstock_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'size_variant')},
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='color_variant',
        ),
    ]
